#!/bin/bash

read -p "Install dependencies? [y/N] "
if [[ $REPLY =~ ^[Yy]$ ]]; then
	sudo apt update
	sudo apt -y install zsh
	sudo apt -y install --no-install-recommends make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev tmux
fi

echo "Populating submodules"
yadm submodule update --recursive --remote
echo "Installing vim-plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
sh -c 'curl -fLo "${HOME}"/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
echo "Installing pyenv"
curl https://pyenv.run | bash

cargo install tealdeer
cargo install vivid
cargo install bat
cargo install exa

echo "Changing shell to zsh..."
chsh -s /bin/zsh

echo "Done! To install tmux plugins, press <prefix>+I in a tmux environment."
