-- plugins - Doom nvim custom plugins
--
-- This file contains all the custom plugins that are not in Doom nvim but that
-- the user requires. All the available fields can be found here
-- https://github.com/wbthomason/packer.nvim#specifying-plugins
--
-- By example, for including a plugin with a dependency on telescope:
-- return {
--     {
--         'user/repository',
--         requires = { 'nvim-lua/telescope.nvim' },
--     },
-- }

return {
    --{
    --    "rcarriga/nvim-dap-ui",
    --    requires = {"mfussenegger/nvim-dap"},
    --    --config = function()
    --    --    require("dapui").setup()
    --    --end,
    --},
    --{
    --    "Pocco81/DAPInstall.nvim",
    --    config = function() require("dap-install").config("ccppr_vsc_dbg", {}) end,
    --        --local dap_install = require("dap-install")
    --        --local dbg_list = require("dap-install.debuggers_list").debuggers
    --        --for debugger, _ in pairs(dbg_list) do
    --        --    dap_install.config(debugger, {})
    --        --end
    --},
    --{
    --    "puremourning/vimspector",
    --    setup = 'vim.cmd([[let g:vimspector_enable_mappings = "HUMAN"]])',
    --},
}
