name: Continuous Integration

on:
  push:
    branches:
      - ci

jobs:
  main:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run polka-dots
      working-directory: ./src/polka-dots
      # DOTS_REPO is the root of the repo folder. This is $HOME by default.
      # DOTS_REPO_GIT_RELATIVE is the path to the .git folder relative to DOTS_REPO. This is ./.local/share/yadm/repo.git by default.
      run: DOTS_REPO=$GITHUB_WORKSPACE DOTS_REPO_GIT_RELATIVE="./.git" cargo run -- deploy
