name: Continuous Integration

on:
  push:
    branches:
      - ci

jobs:
  main:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    container: ubuntu:20.04
    steps:
    - name: Set APT to non-interactive
      run: "echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections"
    - name: Update APT
      run: "apt-get update"
    - name: Install git
      run: "apt-get install -y git"
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run polka-dots
      working-directory: "$GITHUB_WORKSPACE/src/polka-dots"
      run: DOTS_REPO="$GITHUB_WORKSPACE" cargo run -- deploy
